CC=gcc

TARGET=prime_factor binary_of octadecimal_of 

prime_factor:
	$(CC) prime_factor.c ../push.c ../pop.c -o prime_factor

binary_of:
	$(CC) binary_of.c ../push.c ../pop.c -o binary_of

octadecimal_of:
	$(CC) prime_factor.c ../push.c ../pop.c -o octadecimal_of

clean:
	rm $(TARGET)
